export default function Head() {
  return (
    <>
      <title>Nutritiva</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}

// footer, need to check the facebook address
// Hilda no is here anymore
